# Generated by Django 2.0.3 on 2018-03-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ativo'), (2, 'Desativo')], null=True),
        ),
    ]
