# Generated by Django 2.0.3 on 2018-03-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=2)),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=200)),
                ('nascimento', models.DateField()),
                ('mae', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=2)),
                ('situacao', models.CharField(max_length=20)),
                ('consultaID', models.CharField(max_length=50)),
            ],
        ),
    ]
