# Generated by Django 2.0.3 on 2018-03-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpf', '0002_auto_20180308_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoafisica',
            old_name='cpf',
            new_name='cpfnumber',
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='formattedcpf',
            field=models.CharField(default='', max_length=14),
            preserve_default=False,
        ),
    ]
