# Generated by Django 2.0.3 on 2018-03-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpf', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
